apps/filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('main.urls', 'main')),
    url(r'^music-box/', include('music_box.urls', 'music_box')),
    url(r'^advert-box/', include('advert_box.urls', 'advert_box')),
    url(r'', include('profile.urls', 'profile')),

    url(r'', include('django_socketio.urls')),
    url(r'^09061984/filebrowser/', include('filebrowser.urls')),
    url(r'^09061984/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    )

apps/filebrowser/models.py
# This file is only necessary for the tests to work

apps/filebrowser/forms.py
# coding: utf-8

# imports
import re, os

# django imports
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext as _

# filebrowser imports
from apps.filebrowser.settings import MAX_UPLOAD_SIZE, FOLDER_REGEX
from apps.filebrowser.functions import convert_filename

alnum_name_re = re.compile(FOLDER_REGEX)

class MakeDirForm(forms.Form):
    """
    Form for creating Folder.
    """
    
    def __init__(self, path, *args, **kwargs):
        self.path = path
        super(MakeDirForm, self).__init__(*args, **kwargs)
        
    dir_name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_dir_name(self):
        if self.cleaned_data['dir_name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['dir_name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['dir_name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['dir_name'])


class RenameForm(forms.Form):
    """
    Form for renaming Folder/File.
    """
    
    def __init__(self, path, file_extension, *args, **kwargs):
        self.path = path
        self.file_extension = file_extension
        super(RenameForm, self).__init__(*args, **kwargs)
    
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'New Name'), help_text=_('Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif os.path.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name']) + self.file_extension)):
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

apps/filebrowser/views.py
# coding: utf-8

# general imports
import os, re
from time import gmtime, strftime

# django imports
from django.shortcuts import render_to_response, HttpResponse
from django.template import RequestContext as Context
from django.http import HttpResponseRedirect, Http404
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.cache import never_cache
from django.utils.translation import ugettext as _
from django.conf import settings
from django import forms
from django.core.urlresolvers import reverse
from django.core.exceptions import ImproperlyConfigured
from django.dispatch import Signal
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils.encoding import smart_str

from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

# filebrowser imports
from apps.filebrowser import settings as fb_settings
#from filebrowser.conf import fb_settings
from apps.filebrowser.functions import path_to_url, sort_by_attr, get_path, get_file, get_version_path, get_breadcrumbs, get_filterdate, get_settings_var, handle_file_upload, convert_filename
from apps.filebrowser.templatetags.fb_tags import query_helper
from apps.filebrowser.base import FileObject
from apps.filebrowser.decorators import flash_login_required

# Precompile regular expressions
filter_re = []
for exp in fb_settings.EXCLUDE:
   filter_re.append(re.compile(exp))
for k,v in fb_settings.VERSIONS.iteritems():
    exp = (r'_%s.(%s)') % (k, '|'.join(fb_settings.EXTENSION_LIST))
    filter_re.append(re.compile(exp))

def _check_access(request, *path):
    """
    Return absolute file path if access allow or raise exception.
    """
    abs_path = os.path.abspath(os.path.join(
        fb_settings.MEDIA_ROOT, fb_settings.DIRECTORY, *path))
    if not abs_path.startswith(os.path.abspath(os.path.join(
            fb_settings.MEDIA_ROOT, fb_settings.DIRECTORY))):
        # cause any attempt to leave media root directory to fail
        raise Http404
    return abs_path


def browse(request):
    """
    Browse Files/Directories.
    """
    # QUERY / PATH CHECK
    query = request.GET.copy()
    path = get_path(query.get('dir', ''))
    directory = get_path('')

    if 'pop' in query:
        is_popup = True
    else:
        is_popup = False

    if path is not None:
        abs_path = _check_access(request, path)

    if path is None:
        msg = _('The requested Folder does not exist.')
        messages.warning(request, message=msg)
        if directory is None:
            # The DIRECTORY does not exist, raise an error to prevent eternal redirecting.
            raise ImproperlyConfigured, _("Error finding Upload-Folder. Maybe it does not exist?")
        redirect_url = reverse("fb_browse") + query_helper(query, "", "dir")
        return HttpResponseRedirect(redirect_url)
    
    # INITIAL VARIABLES
    results_var = {'results_total': 0, 'results_current': 0, 'delete_total': 0, 'images_total': 0, 'select_total': 0 }
    counter = {}
    for k,v in fb_settings.EXTENSIONS.iteritems():
        counter[k] = 0
    
    dir_list = os.listdir(abs_path)
    files = []

    for file in dir_list:
        
        # EXCLUDE FILES MATCHING VERSIONS_PREFIX OR ANY OF THE EXCLUDE PATTERNS
        filtered = file.startswith('.')
        for re_prefix in filter_re:
            if re_prefix.search(file):
                filtered = True
        if filtered:
            continue
        results_var['results_total'] += 1
        
        # CREATE FILEOBJECT
        fileobject = FileObject(os.path.join(fb_settings.DIRECTORY, path, file))
        
        # FILTER / SEARCH
        append = False
        if fileobject.filetype == request.GET.get('filter_type', fileobject.filetype) and get_filterdate(request.GET.get('filter_date', ''), fileobject.date):
            append = True
        if request.GET.get('q') and not re.compile(request.GET.get('q').lower(), re.M).search(file.lower()):
            append = False
        
        # APPEND FILE_LIST
        if append:
            _type = query.get('type')
            try:
                # COUNTER/RESULTS
                if fileobject.filetype == 'Image':
                    results_var['images_total'] += 1
                if fileobject.filetype != 'Folder':
                    results_var['delete_total'] += 1
                elif fileobject.filetype == 'Folder' and fileobject.is_empty:
                    results_var['delete_total'] += 1
                if _type and _type in fb_settings.SELECT_FORMATS and fileobject.filetype in fb_settings.SELECT_FORMATS[_type]:
                    results_var['select_total'] += 1
                elif not _type:
                    results_var['select_total'] += 1
            except OSError:
                # Ignore items that have problems
                continue
            else:
                files.append(fileobject)
                results_var['results_current'] += 1
        
        # COUNTER/RESULTS
        if fileobject.filetype:
            counter[fileobject.filetype] += 1
    
    # SORTING
    query['o'] = request.GET.get('o', fb_settings.DEFAULT_SORTING_BY)
    query['ot'] = request.GET.get('ot', fb_settings.DEFAULT_SORTING_ORDER)
    files = sort_by_attr(files, request.GET.get('o', fb_settings.DEFAULT_SORTING_BY))
    if not request.GET.get('ot') and fb_settings.DEFAULT_SORTING_ORDER == "desc" or request.GET.get('ot') == "desc":
        files.reverse()
    
    p = Paginator(files, fb_settings.LIST_PER_PAGE)
    try:
        page_nr = request.GET.get('p', '1')
    except:
        page_nr = 1
    try:
        page = p.page(page_nr)
    except (EmptyPage, InvalidPage):
        page = p.page(p.num_pages)

    return render_to_response('suit/index.html', {
        'dir': path,
        'p': p,
        'page': page,
        'results_var': results_var,
        'counter': counter,
        'query': query,
        'title': _(u'FileBrowser'),
        'settings_var': get_settings_var(),
        'breadcrumbs': get_breadcrumbs(query, path),
        'breadcrumbs_title': "",
        'is_popup': is_popup
    }, context_instance=Context(request))
browse = staff_member_required(never_cache(browse))


# mkdir signals
filebrowser_pre_createdir = Signal(providing_args=["path", "dirname"])
filebrowser_post_createdir = Signal(providing_args=["path", "dirname"])

def mkdir(request):
    """
    Make Directory.
    """
    
    from apps.filebrowser.forms import MakeDirForm
    
    # QUERY / PATH CHECK
    query = request.GET
    path = get_path(query.get('dir', ''))

    if 'pop' in query:
        is_popup = True
    else:
        is_popup = False

    if path is None:
        msg = _('The requested Folder does not exist.')
        messages.warning(request,message=msg)
        return HttpResponseRedirect(reverse("fb_browse"))
    abs_path = _check_access(request, path)
    
    if request.method == 'POST':
        form = MakeDirForm(abs_path, request.POST)
        if form.is_valid():
            _new_dir_name = form.cleaned_data['dir_name']
            server_path = _check_access(request, path, _new_dir_name)
            try:
                # PRE CREATE SIGNAL
                filebrowser_pre_createdir.send(sender=request, path=path, dirname=_new_dir_name)
                # CREATE FOLDER
                os.mkdir(server_path)
                os.chmod(server_path, 0775)
                # POST CREATE SIGNAL
                filebrowser_post_createdir.send(sender=request, path=path, dirname=_new_dir_name)
                # MESSAGE & REDIRECT
                msg = _('The Folder %s was successfully created.') % (_new_dir_name)
                messages.success(request,message=msg)
                # on redirect, sort by date desc to see the new directory on top of the list
                # remove filter in order to actually _see_ the new folder
                # remove pagination
                redirect_url = reverse("fb_browse") + query_helper(query, "ot=desc,o=date", "ot,o,filter_type,filter_date,q,p")
                return HttpResponseRedirect(redirect_url)
            except OSError, (errno, strerror):
                if errno == 13:
                    form.errors['dir_name'] = forms.util.ErrorList([_('Permission denied.')])
                else:
                    form.errors['dir_name'] = forms.util.ErrorList([_('Error creating folder.')])
    else:
        form = MakeDirForm(abs_path)
    
    return render_to_response('suit/makedir.html', {
        'form': form,
        'query': query,
        'title': _(u'New Folder'),
        'settings_var': get_settings_var(),
        'breadcrumbs': get_breadcrumbs(query, path),
        'breadcrumbs_title': _(u'New Folder'),
        'is_popup': is_popup
    }, context_instance=Context(request))
mkdir = staff_member_required(never_cache(mkdir))


def upload(request):
    """
    Multipe File Upload.
    """
    
    from django.http import parse_cookie
    
    # QUERY / PATH CHECK
    query = request.GET
    path = get_path(query.get('dir', ''))

    if 'pop' in query:
        is_popup = True
    else:
        is_popup = False

    if path is None:
        msg = _('The requested Folder does not exist.')
        messages.warning(request,message=msg)
        return HttpResponseRedirect(reverse("fb_browse"))
    abs_path = _check_access(request, path)
    
    # SESSION (used for flash-uploading)
    session_key = request.COOKIES.get(settings.SESSION_COOKIE_NAME, None)
    
    return render_to_response('suit/upload.html', {
        'query': query,
        'title': _(u'Select files to upload'),
        'settings_var': get_settings_var(),
        'session_key': session_key,
        'breadcrumbs': get_breadcrumbs(query, path),
        'breadcrumbs_title': _(u'Upload'),
        'is_popup': is_popup
    }, context_instance=Context(request))
upload = staff_member_required(never_cache(upload))


@csrf_exempt
@staff_member_required
def _check_file(request):
    """

apps/filebrowser/templates/suit/append.html
{% load i18n %}

<div class="module">
    <table>
        <caption>{% trans "FileBrowser" %}</caption>
        <tr class="row2">
            <th scope="row"><a href="{% url 'fb_browse' %}">{% trans "FileBrowser" %}</a></th>
            <td> </td>
            <td> </td>
        </tr>
    </table>
</div>

apps/filebrowser/templates/suit/custom_field.html
{% load fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value }}" /><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{% url "fb_browse" %}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="btn btn-info" style="margin-left: 10px; margin-right: 10px;">
    <i class="icon-white icon-search"></i>
</a>
{% ifequal value.filetype "Image" %}
<p class="help" id="help_{{ final_attrs.id }}">
    <a href="{{ value.url_full }}" target="_blank" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" src="{% version value.path final_attrs.ADMIN_THUMBNAIL %}" class="preview" />
    </a>
</p>
{% else %}
<p class="help" id="help_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endifequal %}
{% if final_attrs.DEBUG %}
<p>
    <strong>Path</strong> {{ value.path }}<br />
    <strong>FileType</strong> {{ value.filetype }}<br /><br />
    <strong>Directory</strong> {{ final_attrs.directory }}<br />
    <strong>Extensions</strong> {{ final_attrs.extensions }}<br />
    <strong>Format</strong> {{ final_attrs.format }}
</p>
{% endif %}

apps/filebrowser/templates/suit/index.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags fb_pagination %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
    {% if cl.formset or action_form %}
        {% url 'admin:jsi18n' as jsi18nurl %}
        <script type="text/javascript" src="{{ jsi18nurl|default:'../../jsi18n/' }}"></script>
    {% endif %}
    {{ media.css }}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    {% if is_popup %}
        <script>
            function file_submit(event, elem) {
                event.preventDefault();
                var id = this.name;
                var file_url = $(elem).attr('data-file-url');
                var thumb_url = $(elem).attr('data-thumbnail');
                var file_type = $(elem).attr('data-file-type');
                this.opener.filebrowser_file_submit(id, file_url, thumb_url, file_type);
                this.close();
            }
        </script>
    {% endif %}
    {{ media.js }}
{% endblock %}

{% block bodyclass %}change-list{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block coltype %}flex{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <div class="inner-right-column">
            {% block object-tools %}

                <div class="object-tools">
                    {% block object-tools-items %}
                        <div class="box box-controls">
                            <a href="{% url "fb_upload" %}{% query_string '' 'p' %}" class="btn btn-success">
                                <i class="icon-upload icon-white"></i>&nbsp;
                                {% trans "Upload" %}
                            </a><br>
                            <a href="{% url "fb_mkdir" %}{% query_string '' 'p' %}" class="btn btn-success">
                                <i class="icon-plus-sign icon-white"></i>&nbsp;
                                {% trans "New Folder" %}
                            </a>
                        </div>

                        <div class="box box-controls">
                            <div class="text-center">
                                <a href="{% query_string "" "filter_date,p" %}">{% trans "Any Date" %}</a>
                            </div>
                            <div class="text-center">
                            <a href="{% query_string "" "filter_date,p" %}&amp;filter_date=today">{% trans "Today" %}</a>
                            </div>
                            <div class="text-center">
                                <a href="{% query_string "" "filter_date,p" %}&amp;filter_date=past7days">{% trans "Past 7 days" %}</a>
                            </div>
                            <div class="text-center">
                                <a href="{% query_string "" "filter_date,p" %}&amp;filter_date=thismonth">{% trans "Past 30 days" %}</a>
                            </div>
                            <div class="text-center">
                                <a href="{% query_string "" "filter_date,p" %}&amp;filter_date=thisyear">{% trans "This year" %}</a>
                            </div>
                            <a href="{% query_string "" "filter_type,p" %}" class="btn btn-warning">{% trans "All" %}</a>
                            {% for extension in settings_var.EXTENSIONS %}
                                <a href="{% query_string "" "filter_type,p" %}&amp;filter_type={{ extension }}" class="btn btn-warning">{% trans extension %}</a></li>
                            {% endfor %}
                        </div>
                    {% endblock %}
                </div>

            {% endblock %}
        </div>
        <div class="inner-center-column">
            <div class="module filtered" id="changelist">
                <div class="toolbar-content">


                    {% block search %}
                        <div id="toolbar">
                            <form id="changelist-search" action="." method="get" class="form-inline">
                                <div class="search-container">
                                    <input type="text" size="40" name="q" value="{{ query.q }}" id="searchbar" placeholder="{% block search_placeholder %}{% trans 'keyword'|capfirst %}{% endblock %}"/>&nbsp;
                                    <script type="text/javascript">document.getElementById("searchbar").focus();</script>
                                    {% if query.filter_type %}<input type="hidden" name="filter_type" value="{{ query.filter_type }}" />{% endif %}
                                    {% if query.filter_date %}<input type="hidden" name="filter_date" value="{{ query.filter_date }}" />{% endif %}
                                    {% if query.o %}<input type="hidden" name="o" value="{{ query.o }}" />{% endif %}
                                    {% if query.ot %}<input type="hidden" name="ot" value="{{ query.ot }}" />{% endif %}
                                    {% if query.pop %}<input type="hidden" name="pop" value="{{ query.pop }}" />{% endif %}
                                    {% if query.type %}<input type="hidden" name="type" value="{{ query.type }}" />{% endif %}
                                    {% if query.format %}<input type="hidden" name="format" value="{{ query.format }}" />{% endif %}
                                    {% if query.dir %}<input type="hidden" name="dir" value="{{ query.dir }}" />{% endif %}
                                    <input type="submit" value="{% trans 'Search' %}" class="btn btn-info"/>
                                    {% if results_var.results_total %}
                                        {% if query.filter_type or query.filter_date or query.q %}
                                            <span class="small quiet result-count">{% blocktrans count results_var.results_current as counter %}{{ counter }} result{% plural %}{{ counter }} results{% endblocktrans %} (<a href="{% query_string "" "filter_date,filter_type,q" %}">{% blocktrans with results_var.results_total as full_result_count %}{{ full_result_count }} total{% endblocktrans %}</a>)</span>
                                        {% endif %}
                                    {% endif %}

                                </div>
                            </form>
                        </div>
                    {% endblock %}
                </div>
                {% block result_list %}
                    {% if results_var.results_current %}
                        <div class="results">
                            <table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
                                <thead>
                                <tr>
                                    <!-- SELECT -->
                                    {% if is_popup and results_var.select_total %}<th></th>{% endif %}
                                    <!-- FILETYPE -->
                                    {% ifequal query.o "filetype_checked" %}<th class="sorted {{ query.ot }}ending"><a href="{% query_string "" "o,ot,p" %}&amp;ot={% ifequal query.ot "desc" %}asc{% else %}desc{% endifequal %}&amp;o=filetype_checked">{% trans "Type" %}</a></th>{% endifequal %}
                                    {% ifnotequal query.o "filetype_checked" %}<th><a href="{% query_string "" "o,ot,p" %}&amp;ot=asc&amp;o=filetype_checked">{% trans "Type" %}</a></th>{% endifnotequal %}
                                    <!-- THUMB -->
                                    <th>{% trans "Thumbnail" %}</th>
                                    <!-- FILENAME / DIMENSIONS  -->
                                    {% ifequal query.o "filename_lower" %}<th class="filename sorted {{ query.ot }}ending"><a href="{% query_string "" "o,ot,p" %}&amp;ot={% ifequal query.ot "desc" %}asc{% else %}desc{% endifequal %}&amp;o=filename_lower">{% trans "Filename" %}</a></th>{% endifequal %}
                                    {% ifnotequal query.o "filename_lower" %}<th class="filename"><a href="{% query_string "" "o,ot,p" %}&amp;ot=asc&amp;o=filename_lower">{% trans "Filename" %}</a></th>{% endifnotequal %}
                                    <!-- SIZE -->
                                    {% ifequal query.o "filesize" %}<th class="sorted {{ query.ot }}ending"><a href="{% query_string "" "o,ot,p" %}&amp;ot={% ifequal query.ot "desc" %}asc{% else %}desc{% endifequal %}&amp;o=filesize">{% trans "Size" %}</a></th>{% endifequal %}
                                    {% ifnotequal query.o "filesize" %}<th><a href="{% query_string "" "o,ot,p" %}&amp;ot=asc&amp;o=filesize">{% trans "Size" %}</a></th>{% endifnotequal %}
                                    <!-- DATE -->
                                    {% ifequal query.o "date" %}<th class="sorted {{ query.ot }}ending"><a href="{% query_string "" "o,ot,p" %}&amp;ot={% ifequal query.ot "desc" %}asc{% else %}desc{% endifequal %}&amp;o=date">{% trans "Date" %}</a></th>{% endifequal %}
                                    {% ifnotequal query.o "date" %}<th><a href="{% query_string "" "o,ot,p" %}&amp;ot=asc&amp;o=date">{% trans "Date" %}</a></th>{% endifnotequal %}
                                    <!-- ACTIONS -->
                                    <th>&nbsp;</th>
                                    {% if results_var.delete_total %}<th>&nbsp;</th>{% endif %}
                                    <!-- DEBUG -->
                                    {% if settings_var.DEBUG %}<th>Debug</th>{% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% include "suit/include/filelisting.html" %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="alert alert-block alert-info">
                            <h4>{% trans 'Nothing found' %}!</h4>
                        </div>
                    {% endif %}
                {% endblock %}
                {% block pagination %}
                    {% pagination %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

apps/filebrowser/templates/suit/makedir.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags fb_csrf %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <form action="{% query_string '' 'p' %}" method="post" class="form-horizontal">
            {% fb_csrf_token %}
            <div class="inner-right-column">
                <div class="box save-box">
                    <div class="submit-row clearfix">
                        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-high btn-info" />
                    </div>
                </div>
            </div>
            <div class="inner-center-column">
                <div class="tab-content tab-content-main">
                    {% if form.errors %}
                        <div class="alert alert-error">
                            <strong>{% trans 'Please correct the following errors.' %}</strong>
                        </div>
                    {% endif %}
                    <fieldset class="module aligned">
                        <div class="control-group">
                            <div class="control-label">
                                <label class="required" for="id_dir_name">{{ form.dir_name.label }}</label>
                            </div>
                            <div class="controls">
                                {{ form.dir_name }}
                                {% if form.dir_name.errors %}<span class="help-inline">{{ form.dir_name.errors }}</span>{% endif %}
                                <span class="help-block">
                                    {{ form.dir_name.help_text|safe }}
                                    {% if settings_var.CONVERT_FILENAME %}<br />{% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}{% endif %}
                                </span>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

apps/filebrowser/templates/suit/rename.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags fb_csrf %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}change-form{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post" class="form-horizontal">
            {% fb_csrf_token %}
            <div class="inner-right-column">
                <div class="box save-box">
                    <div class="submit-row clearfix">
                        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-high btn-info" />
                    </div>
                </div>
            </div>
            <div class="inner-center-column">
                <div class="tab-content tab-content-main">
                    {% if form.errors %}
                        <div class="alert alert-error">
                            <strong>{% trans 'Please correct the following errors.' %}</strong>
                        </div>
                    {% endif %}
                    <fieldset class="module aligned">
                        <div class="control-group">
                            <div class="control-label">
                                <label class="required" for="id_dir_name">{{ form.name.label }}</label>
                            </div>
                            <div class="controls">
                                {{ form.name }}{% if file_extension %}<b>{{ file_extension }}</b>{% endif %}
                                {% if form.name.errors %}<span class="help-inline">{{ form.name.errors }}</span>{% endif %}
                                <span class="help-block">
                                    {{ form.name.help_text|safe }}

                                </span>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
{% endblock %}